# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6e5270d630f3a3792b6eac35011ee4c50739d43708204d36597d48e1d7558d75a13fc25956e18dc486adcb2c1639d706f12c73c699fdc23f6dc74dc15f2968b5

test:
  secret_key_base: 442e3d74c510afd7ca047afef1ff92b6d4f1feb00e06645ae532c26c75d7f5f74f8a04b235c9c23239096cae79da2e9232a24636cf18c741e8da92e9004b9ef9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
